const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const authController = require('../controllers/authController');
const authMiddleware = require('../middlewares/authMiddleware');
router.use(authMiddleware.requireAuth);
router.use(authMiddleware.requireAdmin);
router.get('/dashboard', adminController.renderDashboard);
router.get('/invite', adminController.renderInvite);
router.post('/invite', authController.sendInvite);
router.delete('/invite/:inviteId', authController.deleteInvite);
router.get('/vets', adminController.renderVets);
router.get('/vets/new', adminController.renderNewVetForm);
router.get('/vets/:id/edit', adminController.renderEditVetForm);
router.get('/managers', adminController.renderManagers);
router.get('/managers/:id', adminController.getManagerDetails);
router.get('/settings', adminController.renderSettings);
module.exports = router;