const express = require('express');
const router = express.Router();
const authController = require('../controllers/authController');
const authMiddleware = require('../middlewares/authMiddleware');
router.get('/login', authController.renderLogin);
router.post('/login', authController.login);
router.get('/logout', authController.logout);
router.get('/register', authController.renderRegister);
router.post('/register', authController.register);
router.get('/register/invite', authController.renderInviteRegister);
router.post('/invite/:token', authController.registerByInvite);
router.get('/invites/info', authController.getInviteInfo);
router.get('/forgot-password', authController.renderForgotPassword);
router.post('/forgot-password', authController.forgotPassword);
router.get('/reset-password/:token', authController.renderResetPassword);
router.post('/reset-password/:token', authController.resetPassword);
router.get('/profile', authMiddleware.requireAuth, authController.renderProfile);
router.post('/profile', authMiddleware.requireAuth, authController.updateProfile);
router.post('/change-password', authMiddleware.requireAuth, authController.changePassword);
module.exports = router; 