const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const { requireAuth, requireEmployee } = require('../middlewares/authMiddleware');
router.use(requireAuth);
router.use(requireEmployee);
router.get('/clients', adminController.renderClients);
router.get('/clients/:id', adminController.getClientDetails);
router.get('/pets', adminController.renderPets);
router.get('/appointments', adminController.renderAppointments);
module.exports = router;