const express = require('express');
const router = express.Router();
const homeController = require('../controllers/homeController.js');
const appointmentsController = require('../controllers/appointmentsController.js');
router.get('/', homeController.renderHomePage);
router.get('/services', homeController.renderServicesPage);
router.get('/contacts', homeController.renderContactsPage);
router.get('/about', homeController.renderAboutPage);
router.get('/vets', homeController.renderVetsPage);
router.get('/appointment', homeController.renderAppointmentPage);
router.post('/appointment', appointmentsController.createAppointment);
router.get('/thank-you', homeController.renderThankYouPage);
module.exports = router; 